#!/usr/bin/with-contenv bash

if [ ! -d /media/TV ]; then
  echo "Creating /media/TV"
  mkdir -p /media/TV
  chown -R abc:abc /media/TV
fi

if [ ! -d /share/downloads ]; then
  echo "Creating /share/downloads"
  mkdir -p /share/downloads
  chown -R abc:abc /share/downloads
fi

if [ ! -d /share/sonarr/config ]; then
  echo "Creating /share/sonarr/config"
  mkdir -p /share/sonarr/config
  chown -R abc:abc /share/sonarr/config
fi
